[build]
  command = "chmod +x build.sh && ./build.sh"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000

# Handle static assets
[[redirects]]
  from = "/images/*"
  to = "/static/images/:splat"
  status = 200

[[redirects]]
  from = "/logos/*"
  to = "/static/logos/:splat"
  status = 200

[[redirects]]
  from = "/icons/*"
  to = "/static/icons/:splat"
  status = 200