[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000

# Handle static assets - serve from public folder
[[redirects]]
  from = "/images/*"
  to = "/public/images/:splat"
  status = 200

[[redirects]]
  from = "/logos/*"
  to = "/public/logos/:splat"
  status = 200

[[redirects]]
  from = "/icons/*"
  to = "/public/icons/:splat"
  status = 200